### ISSUE TITLE
Change Number of CAVs

### ISSUE THREAD

**Issue by ch3ny1** [hangqiu/AutoCastSim#3]
Hi all,

Thanks for the great work!

I'm wondering if you could give some advice or comments on how to modify the participating CAVs in a particular scenario? For example, if there are three CAVs defined in the scene, can we change the number to eight?

Thanks again!

**Comment by dunesq** [comment]
Hi there,

The scenario has fixed roles for participating vehicles. However, there are background vehicles which are on autopilot. You can adjust the number of background vehicles using flag --bgtraffic
